# Generated by Django 4.1.6 on 2023-02-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeeksModel',
            new_name='uploadfile',
        ),
        migrations.RenameField(
            model_name='uploadfile',
            old_name='geeks_field',
            new_name='file_field',
        ),
    ]
