# Generated by Django 4.1.6 on 2023-03-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_chart_dataset_report_chart_dataset_chart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='svg',
        ),
        migrations.AddField(
            model_name='chart',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/Files/'),
        ),
        migrations.AddField(
            model_name='chart',
            name='title',
            field=models.CharField(default='title unknown', max_length=20),
        ),
    ]
